services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: wildnetwork
      POSTGRES_PASSWORD: wildnetwork
      POSTGRES_DB: wildnetwork
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
